version: "3.7"

networks:
  proxy:
    external: true
  media-network:
    name: media-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:?err}
          gateway: ${DOCKER_GATEWAY:?err}

## Dummy image to be able to run this docker
services:
  config:
    image: hello-world
