version: "3.7"

networks:
  proxy:
    external: true
  media-network:
    name: media-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:?err}
          gateway: ${DOCKER_GATEWAY:?err}

## Dummy image to be able to run this docker
services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - ${WEBUI_PORT_TRAEFIK?:err}:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FOLDER_FOR_CONFIGS:?err}/traefik/traefik.yml:/etc/traefik.yml:ro
      - ${FOLDER_FOR_CONFIGS:?err}/traefik/ssl-certs:/etc/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy
