###########################################################################
###########################################################################
version: "3.7"

services:
  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Bazarr (LinuxServer.io)
  ##  Function: Download subtitles for Radarr and Sonarr
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-bazarr
  ##
  ###########################################################################
  ###########################################################################
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/bazarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    ports:
      - "${WEBUI_PORT_BAZARR:?err}:6767"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
      - TP_THEME=${TP_THEME:?err}
    networks:
      - media-network

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: overseerr (lscr.io/linuxserver)
  ##  Function: Media Request Manager
  ##
  ##  Documentation: https://hub.docker.com/r/linuxserver/overseerr
  ##
  ###########################################################################
  ###########################################################################
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    volumes:
      -  ${FOLDER_FOR_CONFIGS:?err}/overseerr:/config
    ports:
      - ${WEBUI_PORT_OVERSEERR:?err}:5055
    restart: unless-stopped

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Lidarr (LinuxServer.io)
  ##  Function: Music Library Manager
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-lidarr
  ##
  ###########################################################################
  ###########################################################################
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/lidarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    ports:
      - "${WEBUI_PORT_LIDARR:?err}:8686"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=${TP_THEME:?err}
    networks:
      - media-network

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Prowlarr (LinuxServer.io)
  ##  Function: Indexer and Search Manager
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-prowlarr
  ##
  ###########################################################################
  ###########################################################################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/prowlarr:/config
    ports:
      - "${WEBUI_PORT_PROWLARR:?err}:9696"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${TP_THEME:?err}
    networks:
      - media-network

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: qBittorrent (LinuxServer.io)
  ##  Function: Torrent Download Client
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-qbittorrent
  ##
  ###########################################################################
  ###########################################################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/qbittorrent:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - WEBUI_PORT=${WEBUI_PORT_QBITTORRENT:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent
      - TP_THEME=${TP_THEME:?err}

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Radarr (LinuxServer.io)
  ##  Function: Movie Library Manager
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-radarr
  ##
  ###########################################################################
  ###########################################################################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/radarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    ports:
      - "${WEBUI_PORT_RADARR:?err}:7878"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${TP_THEME:?err}
    networks:
      - media-network

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Readarr (LinuxServer.io)
  ##  Function: Book Library Manager
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-readarr
  ##
  ###########################################################################
  ###########################################################################
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/readarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    ports:
      - "${WEBUI_PORT_READARR:?err}:8787"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:readarr
      - TP_THEME=${TP_THEME:?err}
    networks:
      - media-network

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Sonarr (LinuxServer.io)
  ##  Function: Series Library Manager (TV Shows)
  ##
  ##  Documentation: https://docs.linuxserver.io/images/docker-sonarr
  ##
  ###########################################################################
  ###########################################################################
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/sonarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    ports:
      - "${WEBUI_PORT_SONARR:?err}:8989"
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${TP_THEME:?err}
    networks:
      - media-network

  ###########################################################################
  ###########################################################################
  ##
  ##  Docker Compose File: Plex (LinuxServer.io)
  ##  Function: Plex media server
  ##
  ##  Documentation: https://github.com/louislam/uptime-kuma/wiki
  ##  https://www.plex.tv/
  ##
  ###########################################################################
  ###########################################################################
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - VERSION=docker
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/plex:/config
      - ${FOLDER_FOR_MEDIA:?err}/media:/data/media
    restart: unless-stopped
